package ec.facturacion.electronica.ws.recepcion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-10-14T21:10:58.731-05:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://ec.gob.sri.ws.recepcion", name = "RecepcionComprobantes")
@XmlSeeAlso({ObjectFactory.class})
public interface RecepcionComprobantes {

    @WebMethod
    @RequestWrapper(localName = "validarComprobante", targetNamespace = "http://ec.gob.sri.ws.recepcion", className = "ec.facturacion.electronica.ws.recepcion.ValidarComprobante")
    @ResponseWrapper(localName = "validarComprobanteResponse", targetNamespace = "http://ec.gob.sri.ws.recepcion", className = "ec.facturacion.electronica.ws.recepcion.ValidarComprobanteResponse")
    @WebResult(name = "RespuestaRecepcionComprobante", targetNamespace = "")
    public ec.facturacion.electronica.ws.recepcion.RespuestaSolicitud validarComprobante(
        @WebParam(name = "xml", targetNamespace = "")
        byte[] xml
    );
}
