package ec.facturacion.electronica.ws.autorizacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-10-14T21:18:33.166-05:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://ec.gob.sri.ws.autorizacion", name = "AutorizacionComprobantes")
@XmlSeeAlso({ObjectFactory.class})
public interface AutorizacionComprobantes {

    @WebMethod
    @RequestWrapper(localName = "autorizacionComprobante", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "ec.facturacion.electronica.ws.autorizacion.AutorizacionComprobante")
    @ResponseWrapper(localName = "autorizacionComprobanteResponse", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "ec.facturacion.electronica.ws.autorizacion.AutorizacionComprobanteResponse")
    @WebResult(name = "RespuestaAutorizacionComprobante", targetNamespace = "")
    public ec.facturacion.electronica.ws.autorizacion.RespuestaComprobante autorizacionComprobante(
        @WebParam(name = "claveAccesoComprobante", targetNamespace = "")
        java.lang.String claveAccesoComprobante
    );

    @WebMethod
    @RequestWrapper(localName = "autorizacionComprobanteLote", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "ec.facturacion.electronica.ws.autorizacion.AutorizacionComprobanteLote")
    @ResponseWrapper(localName = "autorizacionComprobanteLoteResponse", targetNamespace = "http://ec.gob.sri.ws.autorizacion", className = "ec.facturacion.electronica.ws.autorizacion.AutorizacionComprobanteLoteResponse")
    @WebResult(name = "RespuestaAutorizacionLote", targetNamespace = "")
    public ec.facturacion.electronica.ws.autorizacion.RespuestaLote autorizacionComprobanteLote(
        @WebParam(name = "claveAccesoLote", targetNamespace = "")
        java.lang.String claveAccesoLote
    );
}
